// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file api/v1/ai_service.proto (package memos.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import { file_google_api_client } from "../../google/api/client_pb";
import { file_google_api_field_behavior } from "../../google/api/field_behavior_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file api/v1/ai_service.proto.
 */
export const file_api_v1_ai_service: GenFile = /*@__PURE__*/
  fileDesc("ChdhcGkvdjEvYWlfc2VydmljZS5wcm90bxIMbWVtb3MuYXBpLnYxIkkKEVRyYW5zY3JpYmVSZXF1ZXN0EjQKBWF1ZGlvGAEgASgLMiAubWVtb3MuYXBpLnYxLlRyYW5zY3JpcHRpb25BdWRpb0ID4EECIncKElRyYW5zY3JpcHRpb25BdWRpbxIWCgdjb250ZW50GAEgASgMQgPgQQRIABINCgN1cmkYAiABKAlIABIVCghmaWxlbmFtZRgDIAEoCUID4EEBEhkKDGNvbnRlbnRfdHlwZRgEIAEoCUID4EEBQggKBnNvdXJjZSIiChJUcmFuc2NyaWJlUmVzcG9uc2USDAoEdGV4dBgBIAEoCSJGChRHZW5lcmF0ZUltYWdlUmVxdWVzdBITCgZwcm9tcHQYASABKAlCA+BBAhIZCgxhc3BlY3RfcmF0aW8YAiABKAlCA+BBASKwAQoVR2VuZXJhdGVJbWFnZVJlc3BvbnNlEg8KB2NvbnRlbnQYASABKAwSFAoMY29udGVudF90eXBlGAIgASgJEhAKCGZpbGVuYW1lGAMgASgJEg0KBW1vZGVsGAQgASgJEhUKDWdlbmVyYXRpb25faWQYBSABKAkSGQoRc2V0dGxlbWVudF9zdGF0dXMYBiABKAkSDAoEY29zdBgHIAEoCRIPCgdjcmVkaXRzGAggASgJMo8CCglBSVNlcnZpY2USeQoKVHJhbnNjcmliZRIfLm1lbW9zLmFwaS52MS5UcmFuc2NyaWJlUmVxdWVzdBogLm1lbW9zLmFwaS52MS5UcmFuc2NyaWJlUmVzcG9uc2UiKNpBBWF1ZGlvgtPkkwIaOgEqIhUvYXBpL3YxL2FpOnRyYW5zY3JpYmUShgEKDUdlbmVyYXRlSW1hZ2USIi5tZW1vcy5hcGkudjEuR2VuZXJhdGVJbWFnZVJlcXVlc3QaIy5tZW1vcy5hcGkudjEuR2VuZXJhdGVJbWFnZVJlc3BvbnNlIizaQQZwcm9tcHSC0+STAh06ASoiGC9hcGkvdjEvYWk6Z2VuZXJhdGVJbWFnZUKmAQoQY29tLm1lbW9zLmFwaS52MUIOQWlTZXJ2aWNlUHJvdG9QAVowZ2l0aHViLmNvbS91c2VtZW1vcy9tZW1vcy9wcm90by9nZW4vYXBpL3YxO2FwaXYxogIDTUFYqgIMTWVtb3MuQXBpLlYxygIMTWVtb3NcQXBpXFYx4gIYTWVtb3NcQXBpXFYxXEdQQk1ldGFkYXRh6gIOTWVtb3M6OkFwaTo6VjFiBnByb3RvMw", [file_google_api_annotations, file_google_api_client, file_google_api_field_behavior]);

/**
 * @generated from message memos.api.v1.TranscribeRequest
 */
export type TranscribeRequest = Message<"memos.api.v1.TranscribeRequest"> & {
  /**
   * Required. Audio input.
   *
   * @generated from field: memos.api.v1.TranscriptionAudio audio = 1;
   */
  audio?: TranscriptionAudio | undefined;
};

/**
 * Describes the message memos.api.v1.TranscribeRequest.
 * Use `create(TranscribeRequestSchema)` to create a new message.
 */
export const TranscribeRequestSchema: GenMessage<TranscribeRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 0);

/**
 * @generated from message memos.api.v1.TranscriptionAudio
 */
export type TranscriptionAudio = Message<"memos.api.v1.TranscriptionAudio"> & {
  /**
   * @generated from oneof memos.api.v1.TranscriptionAudio.source
   */
  source: {
    /**
     * Inline audio bytes.
     *
     * @generated from field: bytes content = 1;
     */
    value: Uint8Array;
    case: "content";
  } | {
    /**
     * URI for audio content. Reserved for future use.
     *
     * @generated from field: string uri = 2;
     */
    value: string;
    case: "uri";
  } | { case: undefined; value?: undefined };

  /**
   * Optional. The uploaded filename.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Optional. The MIME type of the input audio.
   *
   * @generated from field: string content_type = 4;
   */
  contentType: string;
};

/**
 * Describes the message memos.api.v1.TranscriptionAudio.
 * Use `create(TranscriptionAudioSchema)` to create a new message.
 */
export const TranscriptionAudioSchema: GenMessage<TranscriptionAudio> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 1);

/**
 * @generated from message memos.api.v1.TranscribeResponse
 */
export type TranscribeResponse = Message<"memos.api.v1.TranscribeResponse"> & {
  /**
   * The transcribed text.
   *
   * @generated from field: string text = 1;
   */
  text: string;
};

/**
 * Describes the message memos.api.v1.TranscribeResponse.
 * Use `create(TranscribeResponseSchema)` to create a new message.
 */
export const TranscribeResponseSchema: GenMessage<TranscribeResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 2);

/**
 * @generated from message memos.api.v1.GenerateImageRequest
 */
export type GenerateImageRequest = Message<"memos.api.v1.GenerateImageRequest"> & {
  /**
   * Required. Natural-language description of the image to generate.
   *
   * @generated from field: string prompt = 1;
   */
  prompt: string;

  /**
   * Optional. Output aspect ratio. Supported values: 1:1, 4:3, 3:4, 16:9, 9:16.
   *
   * @generated from field: string aspect_ratio = 2;
   */
  aspectRatio: string;
};

/**
 * Describes the message memos.api.v1.GenerateImageRequest.
 * Use `create(GenerateImageRequestSchema)` to create a new message.
 */
export const GenerateImageRequestSchema: GenMessage<GenerateImageRequest> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 3);

/**
 * @generated from message memos.api.v1.GenerateImageResponse
 */
export type GenerateImageResponse = Message<"memos.api.v1.GenerateImageResponse"> & {
  /**
   * Generated image bytes.
   *
   * @generated from field: bytes content = 1;
   */
  content: Uint8Array;

  /**
   * MIME type of the generated image.
   *
   * @generated from field: string content_type = 2;
   */
  contentType: string;

  /**
   * Suggested filename for attaching the image to a memo.
   *
   * @generated from field: string filename = 3;
   */
  filename: string;

  /**
   * Exact Anyhost Catalog model ID that generated the image.
   *
   * @generated from field: string model = 4;
   */
  model: string;

  /**
   * Anyhost Generation ID for usage and settlement lookup.
   *
   * @generated from field: string generation_id = 5;
   */
  generationId: string;

  /**
   * Settlement state returned by Anyhost.
   *
   * @generated from field: string settlement_status = 6;
   */
  settlementStatus: string;

  /**
   * Final USD cost. Populated only when settlement_status is "settled".
   *
   * @generated from field: string cost = 7;
   */
  cost: string;

  /**
   * Final Model Credit debit. Populated only when settlement_status is "settled".
   *
   * @generated from field: string credits = 8;
   */
  credits: string;
};

/**
 * Describes the message memos.api.v1.GenerateImageResponse.
 * Use `create(GenerateImageResponseSchema)` to create a new message.
 */
export const GenerateImageResponseSchema: GenMessage<GenerateImageResponse> = /*@__PURE__*/
  messageDesc(file_api_v1_ai_service, 4);

/**
 * @generated from service memos.api.v1.AIService
 */
export const AIService: GenService<{
  /**
   * Transcribe transcribes an audio file using an instance AI provider.
   *
   * @generated from rpc memos.api.v1.AIService.Transcribe
   */
  transcribe: {
    methodKind: "unary";
    input: typeof TranscribeRequestSchema;
    output: typeof TranscribeResponseSchema;
  },
  /**
   * GenerateImage generates an image with the instance's managed image model.
   *
   * @generated from rpc memos.api.v1.AIService.GenerateImage
   */
  generateImage: {
    methodKind: "unary";
    input: typeof GenerateImageRequestSchema;
    output: typeof GenerateImageResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_api_v1_ai_service, 0);

